=== Automa-Git/Super-Flash-DEMO/ITA/StartSF/XML/recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="recipes">
	<xs:complexType> 
	 <xs:sequence>
		<xs:element name="recipe" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="ingredients">
				  <xs:complexType>
				   <xs:sequence>
						<xs:element name="ingredient" maxOccurs="unbounded">
							<xs:complexType>
							<xs:simpleContent>
								<xs:extension base="xs:string">
									<xs:attribute name="um" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="g"/>
											<xs:enumeration value="n"/>
										</xs:restriction>
									</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="qta" type="xs:integer" use="required"/>
									<xs:attribute name="kcal" type="xs:decimal" use="required"/>
								</xs:extension>
							</xs:simpleContent>
							</xs:complexType>
						</xs:element>
				   </xs:sequence>
				  </xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="title" type="xs:string" use="required" /> 
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Automa-Git/Super-Flash-DEMO/ITA/StartSF/XML/recipes.xml
<?xml version="1.0"?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipes.xsd">
	<recipe title="Fruit Tart">
		<ingredients>
			<ingredient um="g" qta="4   " kcal="13.6  ">Flour</ingredient>
			<ingredient um="g" qta="100 " kcal="390.0 ">Sugar</ingredient>
			<ingredient um="g" qta="1   " kcal="90.0  ">Eggs</ingredient>
			<ingredient um="g" qta="16  " kcal="9.6   ">Yeast</ingredient>
			<ingredient um="g" qta="100 " kcal="760.0 ">Butter</ingredient>
			<ingredient um="g" qta="0   " kcal="0.0   ">Milk</ingredient>
			<ingredient um="g" qta="0   " kcal="0.0   ">Jam</ingredient>
			<ingredient um="g" qta="0   " kcal="0.0   ">Chocolate</ingredient>
			<ingredient um="g" qta="500 " kcal="1250.0">Fruits</ingredient>
			<ingredient um="g" qta="0   " kcal="0.0   ">Liquor</ingredient>
		</ingredients>
	</recipe>
	<recipe title="Blueberry Pie">
		<ingredients>
			<ingredient um="g" qta="1   " kcal="3.4   ">Flour</ingredient>
			<ingredient um="g" qta="250 " kcal="975.0 ">Sugar</ingredient>
			<ingredient um="g" qta="2   " kcal="180.0 ">Eggs</ingredient>
			<ingredient um="g" qta="8   " kcal="4.8   ">Yeast</ingredient>
			<ingredient um="g" qta="200 " kcal="1520.0">Butter</ingredient>
			<ingredient um="g" qta="0   " kcal="0.0   ">Milk</ingredient>
			<ingredient um="g" qta="100 " kcal="220.0 ">Jam</ingredient>
			<ingredient um="g" qta="0   " kcal="0.0   ">Chocolate</ingredient>
			<ingredient um="g" qta="350 " kcal="875.0 ">Fruits</ingredient>
			<ingredient um="g" qta="111 " kcal="144.3 ">Liquor</ingredient>
		</ingredients>
	</recipe>
</recipes>
